/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.view;

import org.model.Conexao;
import org.model.Funcionario;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno Manha
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCadastrarFu = new javax.swing.JButton();
        jtfMatFu = new javax.swing.JTextField();
        jlbMatFu = new javax.swing.JLabel();
        jtfTelFu = new javax.swing.JTextField();
        jbLimparFu = new javax.swing.JButton();
        jlbNomeFu = new javax.swing.JLabel();
        jcbTipoFu = new javax.swing.JComboBox();
        jlbTipoFu = new javax.swing.JLabel();
        jtfEmailFu = new javax.swing.JTextField();
        jtfNomeFu = new javax.swing.JTextField();
        jlbTelFu = new javax.swing.JLabel();
        jlbEmailFu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 73, 93));

        jbCadastrarFu.setBackground(java.awt.Color.white);
        jbCadastrarFu.setForeground(new java.awt.Color(52, 73, 93));
        jbCadastrarFu.setText("Cadastrar");
        jbCadastrarFu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarFuActionPerformed(evt);
            }
        });

        jlbMatFu.setFont(new java.awt.Font("Laksaman", 0, 14)); // NOI18N
        jlbMatFu.setForeground(java.awt.Color.white);
        jlbMatFu.setText("Matricula:");

        jbLimparFu.setBackground(java.awt.Color.white);
        jbLimparFu.setForeground(new java.awt.Color(52, 73, 93));
        jbLimparFu.setText("Limpar");
        jbLimparFu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparFuActionPerformed(evt);
            }
        });

        jlbNomeFu.setFont(new java.awt.Font("Laksaman", 0, 14)); // NOI18N
        jlbNomeFu.setForeground(java.awt.Color.white);
        jlbNomeFu.setText("Nome:");

        jcbTipoFu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Funcionário", "Não Funcionário" }));
        jcbTipoFu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoFuActionPerformed(evt);
            }
        });

        jlbTipoFu.setFont(new java.awt.Font("Laksaman", 0, 14)); // NOI18N
        jlbTipoFu.setForeground(java.awt.Color.white);
        jlbTipoFu.setText("Tipo:");

        jlbTelFu.setFont(new java.awt.Font("Laksaman", 0, 14)); // NOI18N
        jlbTelFu.setForeground(java.awt.Color.white);
        jlbTelFu.setText("Telefone:");

        jlbEmailFu.setFont(new java.awt.Font("Laksaman", 0, 14)); // NOI18N
        jlbEmailFu.setForeground(java.awt.Color.white);
        jlbEmailFu.setText("Email:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbLimparFu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCadastrarFu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbEmailFu)
                            .addComponent(jlbNomeFu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jtfNomeFu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfEmailFu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbTelFu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfTelFu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbMatFu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfMatFu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbTipoFu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbTipoFu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNomeFu)
                    .addComponent(jtfNomeFu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbEmailFu)
                    .addComponent(jtfEmailFu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTelFu)
                    .addComponent(jtfTelFu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbMatFu)
                    .addComponent(jtfMatFu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTipoFu)
                    .addComponent(jcbTipoFu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbLimparFu)
                    .addComponent(jbCadastrarFu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimparFuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparFuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbLimparFuActionPerformed

    private void jbCadastrarFuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarFuActionPerformed
        int ids;
        Object teste;
        String t;

        teste = (jcbTipoFu.getSelectedItem());
        t = String.valueOf(teste);

        try {
            ids = Integer.parseInt(jtfMatFu.getText());

            Connection conexao = Conexao.getConexao();
            Funcionario livro = new Funcionario(ids, jtfNomeFu.getText(), jtfEmailFu.getText(), jtfTelFu.getText());
            switch (t) { // Inserindo baseado no tipo
                case "Funcionário":
                    livro.inserir(conexao, "f");
                    break;
                case "Não Funcionário":
                    livro.inserir(conexao, "v");
                    break;
            }
            JOptionPane.showMessageDialog(null, "Usuario inserido com sucesso");
            dispose();

        } catch (SQLException ex) {
            Logger.getLogger(CadastroFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            System.err.println("Erro");
        }
    }//GEN-LAST:event_jbCadastrarFuActionPerformed

    private void jcbTipoFuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoFuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTipoFuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCadastrarFu;
    private javax.swing.JButton jbLimparFu;
    private javax.swing.JComboBox jcbTipoFu;
    private javax.swing.JLabel jlbEmailFu;
    private javax.swing.JLabel jlbMatFu;
    private javax.swing.JLabel jlbNomeFu;
    private javax.swing.JLabel jlbTelFu;
    private javax.swing.JLabel jlbTipoFu;
    private javax.swing.JTextField jtfEmailFu;
    private javax.swing.JTextField jtfMatFu;
    private javax.swing.JTextField jtfNomeFu;
    private javax.swing.JTextField jtfTelFu;
    // End of variables declaration//GEN-END:variables
}
